// SINTAXIS SIMILARES ENTRE JAVA Y JAVASCRIPT

// OPERADORES SIMPLIFICADOS 
/* 
+=
-=
*=
/=

OPERADORES ARITMÉTICOS
+
-
*
/

OPERADORES DE ASIGNACIÓN
= 

OPERADORES DE COMPARACIÓN 

== IGUA, DEVUEVE UN RESULTADO BOOLEANO

DOCUMENTAR 

// PARA UNA LINEA DE COMENTARIO 
/* PARA MULTIPLES LINEAS DE COMENTARIOS */

/* SECUENCIA DE ESCAPE

/' MOSTRAR UNA COMILLA SIMPLE DENTRO DE UNA CADENA EN LA SALIDA DE INFORMACIÓN
/" MOSTRAR DOBLE COMILLA DENTRO DE UAN CADENA EN LA SALUDA DE INFORMACIÓN
/ BARRA INVERTIDA, ES PARA MOSTRAR UN BACK SLASH
\ ESTO ES UN SALTO DE LÍNEA
\r RETORNO
\t TABULADOR
\f SALTO DE PÁGINA

OPERADOR DE AUMENTO 
++ 

OPERADOR DE DECREENTO
--

*/